services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: notification-kafka
    ports:
      - '9092:9092'

  mailpit:
    image: axllent/mailpit:latest
    container_name: notification-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"