packages:
  - 'packages/*'
  - 'libs/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  nx: true
  unrs-resolver: false
  '@nestjs/core': false
  esbuild: true
  msgpackr-extract: true
  workerd: true
  '@prisma/engines': true
  prisma: true
