packages:
  - 'packages/*'
  - 'libs/*'
  - 'email-worker'
  - 'email-worker-e2e'
  - 'retry-scheduler'
  - 'retry-scheduler-e2e'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  nx: true
  unrs-resolver: false
  '@nestjs/core': false
  esbuild: true
  msgpackr-extract: true
  workerd: true
  '@prisma/engines': true
  prisma: true
