apiVersion: v1
kind: Service

metadata:
  name: gateway
  namespace: notification-platform

spec:
  selector:
    app: gateway

  ports:
    - name: http
      port: 3000
      targetPort: 3000

  type: ClusterIP
