apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    {{- include "notification-platform.labels" . | nindent 4 }}
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: {{ .Values.kafka.service.clientPort }}
      targetPort: {{ .Values.kafka.service.clientPort }}